version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - shared
  kafka:
    image: wurstmeister/kafka:0.10.0.0
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "kgd-load:20:1,kgd:20:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared

networks:
  shared:
    driver: bridge
