apiVersion: batch/v1
kind: Job
metadata:
  name: util
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: util
        image: blawlor/kafka-util:latest
      restartPolicy: Never

