apiVersion: batch/v1
kind: Job
metadata:
  name: gccontent-experiment
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: gccontent-experiment
        image: blawlor/experiment:latest
        command: ["./experiment.sh"]
        args: ["gccontent", "gccontent-instructions", "$NUMBER_OF_MESSAGES", "refseq-gccontent"]
      restartPolicy: Never

